# Generated by Django 2.1.7 on 2019-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='CI',
            field=models.TextField(default='Add your discord, steam name and other ways to contact you here!', max_length=5000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='GP',
            field=models.TextField(default='Add the games you are playing here!', max_length=5000),
        ),
    ]
