# Generated by Django 2.1.7 on 2019-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_friendrequests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequests',
            name='friendship',
            field=models.BooleanField(default=False),
        ),
    ]
