# Generated by Django 2.1.7 on 2019-02-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GENERAL', 'general'), ('SANDBOX', 'sandbox'), ('SHOOTER', 'shooter'), ('STRATEGY', 'strategy')], default='GENERAL', max_length=64)),
                ('question', models.CharField(max_length=500)),
                ('answers', models.CharField(max_length=1000)),
            ],
        ),
    ]
