# Generated by Django 2.1.7 on 2019-03-02 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20190228_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': ('Categories',),
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='type',
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Categories', verbose_name='Question Category'),
            preserve_default=False,
        ),
    ]
