# Generated by Django 2.1.7 on 2019-03-02 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20190301_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='answers',
            name='belongsToWhichQuestion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questions', verbose_name='Which question does this answer belong to?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='answertype',
            field=models.CharField(choices=[('SINGLE', 'Single Answer'), ('MULTIPLE', 'Multiple Answers'), ('SORTABLE', 'Sortable/Rateable Answers')], default='SINGLEANSWER', max_length=64),
        ),
    ]
