# Generated by Django 2.1.7 on 2019-03-03 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20190302_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseIntance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, verbose_name='User who answered the question')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Answers', verbose_name='Question that was answered')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='answertype',
            field=models.CharField(choices=[('SINGLE', 'Can only pick one answer'), ('MULTIPLE', 'Can pick multiple answers'), ('SORTABLE', 'The answers are sortable or rateable')], default='SINGLEANSWER', max_length=64, verbose_name='Answer Type'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Categories', verbose_name='Question Category'),
        ),
        migrations.AddField(
            model_name='responseintance',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questions', verbose_name='Question that was answered'),
        ),
    ]
