# Generated by Django 2.1.7 on 2019-03-03 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20190303_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseinstances',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who answered the question'),
        ),
    ]
