# Generated by Django 2.1.7 on 2019-04-15 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20190303_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=250, unique=True, verbose_name='Attribute')),
            ],
            options={
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='questions',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.Attribute', verbose_name='What player attribute does this question guage?'),
        ),
    ]
