# Generated by Django 2.1.7 on 2019-04-08 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='neighbors',
            field=models.ManyToManyField(related_name='neighbors', to=settings.AUTH_USER_MODEL),
        ),
    ]
