# Generated by Django 2.1.7 on 2019-04-15 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0013_auto_20190414_1915'),
        ('Matchmaking', '0002_matchmaking_neighbors'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchmakingAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KNNvalue', models.FloatField(verbose_name="What is the KNN value of this user's attribute?")),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Attribute', verbose_name='What player attribute is being guaged?')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
