# Generated by Django 2.1.7 on 2019-04-15 02:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0013_auto_20190414_1915'),
        ('Matchmaking', '0003_matchmakingattributes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MatchmakingAttributes',
            new_name='MatchmakingAttribute',
        ),
    ]
