# Generated by Django 2.1.7 on 2019-04-22 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Matchmaking', '0004_auto_20190414_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggressionRating', models.IntegerField(default=0)),
                ('skillRating', models.IntegerField(default=0)),
                ('teamworkRating', models.IntegerField(default=0)),
                ('communicationRating', models.IntegerField(default=0)),
                ('userBeingRated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userBeingRated', to=settings.AUTH_USER_MODEL)),
                ('userDoingTheRating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userDoingTheRating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
