# Generated by Django 2.1.7 on 2019-03-12 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('steam_id', models.CharField(blank=True, default='NA', max_length=200)),
                ('ps_network_id', models.CharField(blank=True, default='NA', max_length=200)),
                ('xbox_id', models.CharField(blank=True, default='NA', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=1)),
                ('q2', models.CharField(max_length=1)),
                ('q3', models.CharField(max_length=1)),
                ('q4', models.CharField(max_length=1)),
                ('q5', models.CharField(max_length=1)),
                ('q6', models.CharField(max_length=1)),
                ('q7', models.CharField(max_length=1)),
                ('q8', models.CharField(max_length=1)),
                ('q9', models.CharField(max_length=1)),
                ('q10', models.CharField(max_length=1)),
                ('q11', models.CharField(max_length=1)),
                ('q12', models.CharField(max_length=1)),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Gamer')),
            ],
        ),
        migrations.CreateModel(
            name='SelfEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=1)),
                ('q2', models.CharField(max_length=1)),
                ('q3', models.CharField(max_length=1)),
                ('q4', models.CharField(max_length=1)),
                ('q5', models.CharField(max_length=1)),
                ('q6', models.CharField(max_length=1)),
                ('q7', models.CharField(max_length=1)),
                ('q8', models.CharField(max_length=1)),
                ('q9', models.CharField(max_length=1)),
                ('q10', models.CharField(max_length=1)),
                ('q11', models.CharField(max_length=1)),
                ('q12', models.CharField(max_length=1)),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Gamer')),
            ],
        ),
    ]
