# Generated by Django 2.1.7 on 2019-03-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamer',
            old_name='name',
            new_name='tag',
        ),
    ]
