# Generated by Django 2.1.7 on 2019-03-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190312_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='name',
            field=models.CharField(blank=True, default='Bob', max_length=100),
        ),
    ]
